---
# ansible-playbook -i inventory/default -i inventory/test_server test.yml

- hosts: all
  roles:
    # - post-install

- hosts: all
  become: true
  roles:
    - user-gestion
    # - secure-grub
    - docker