---
# ansible-playbook -i inventory/default -i inventory/test_server test.yml

- hosts: all
  roles:
    # - post-install

- hosts: all
  become: true
  roles:
    # - user-gestion
    # - secure-grub

- hosts:
    - docker
    - wiki
    - wordpress
  become: true
  roles:
    # - container_runtime

- hosts: wiki
  become: true
  roles:
    - role: amaelfr.deploy_docker_compose
      vars: # add runtime_user to discover dockersocket !!!! when DOCKER_HOST not set
        src: https://github.com/amaelFr/enterprise_tools.git
          # src_branch:
          # src_commit:
        name: wiki
        runtime_user: "{{ wiki_service_user|d(omit) }}"
        files:
          - wiki/wikijs/docker-compose.yml
        # command_before_build:
        # command_on_build: ok
        # command_build: ok
        # command_before_start: ok
        # command_on_start: ok
        # command_start: ok
        # command_after_start:
        #   - destination: keycloak
        #     user: root
        #     command: echo "192.168.204.178 ipa.{{ domain.name }}" >> /etc/hosts
        # command_down: ok
        # command_clean: ok
        # use_runtime_user_socket: true
        general_environment:
          WIKI_INTERFACE: "{{ wiki_interface|d(omit) }}"
          WIKI_PORT: "{{ wiki_port|d(omit) }}"
