---
- hosts: wiki
  become: true
  roles:
    - role: amaelfr.deploy_docker_compose
      vars: # add runtime_user to discover dockersocket !!!! when DOCKER_HOST not set
        src: https://github.com/amaelFr/enterprise_tools.git
          # src_branch:
          # src_commit:
        name: wiki
        runtime_user: "{{ wiki_service_user|d(omit) }}"
        files:
          - wiki/wikijs/docker-compose.yml
        # use_runtime_user_socket: true
        # container_remove_volume: true
        general_environment:
          WIKI_INTERFACE: "{{ wiki_interface|d(omit) }}"
          WIKI_PORT: "{{ wiki_port|d(omit) }}"