#!/bin/sh

. /etc/update-motd.d/colors

echo "Welcome on ${Red}"

if command -v toilet >/dev/null 2>&1; then
    toilet " $(hostname)"
elif command -v banner >/dev/null 2>&1; then
    ## deb package sysvbanner
    banner " $(hostname)"
elif command -v figlet >/dev/null 2>&1; then
    figlet " $(hostname)"
else
    echo "          $(hostname)"
fi

echo ${NC}
