---
- name: Get docker prerequis
  apt:
    name:
      - gnupg2
      - uidmap
    state: present
  when: not (container.podman|d(false) or container.uninstall|d(false))

# # 
# - name: debian 10 compatibility
#   when: ansible_distribution == 'Debian' and ansible_facts['distribution_major_version'] < 11 or ansible_distribution == 'Ubuntu' and ansible_facts['distribution_major_version'] < 20.04
#   apt:
#     name:
#       - slirp4netns
#     state: present

- name: Remove docker packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }}/gpg
    state: "{{ 'absent' if container.podman|d(false) or container.uninstall|d(false) else 'present' }}"

- name: Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }} {{ ansible_facts['distribution_release'] }} stable"
    state: "{{ 'absent' if container.podman|d(false) or container.uninstall|d(false) else 'present' }}"

- name: Update apt packages
  apt:
    update_cache: true
    force_apt_get: true