---
# tasks file for docker

- include_tasks: "{{ ansible_facts['os_family']|lower }}_based.yml"

- name: Install python3-pip
  package:
    name:
      - python3-pip
    state: present

- import_tasks: docker.yml
- import_tasks: podman.yml

- name: Container runtime systemd
  ansible.builtin.systemd:
    name: "{{ 'podman' if container.podman|d(false) else 'docker' }}"
    state: "{{ 'stopped' if container.rootless|d(true) or container.users|d([])|int > 0 else 'started' }}"
    enabled: "{{ not (container.rootless|d(true) or container.users|d([])|int > 0) }}"

